#ifndef _ES_MANAGER_VERSION_H_
#define _ES_MANAGER_VERSION_H_

#define ESM_VERSION_MAJOR 1
#define ESM_VERSION_MINOR 16
#define ESM_VERSION_BUILD 2
#define ESM_VERSION_CODE 33

#endif // _ES_MANAGER_VERSION_H_
