#ifndef _ES_MANAGER_VERSION_H_
#define _ES_MANAGER_VERSION_H_

#define ESM_VERSION_MAJOR 1
#define ESM_VERSION_MINOR 15
#define ESM_VERSION_BUILD 1
#define ESM_VERSION_CODE 32

#endif // _ES_MANAGER_VERSION_H_
