#!/bin/sh

# chown -R mobile.staff /Applications/ESManager.app

chown root:wheel /Applications/ESManager.app/ESManager.exe
chmod 6755 /Applications/ESManager.app/ESManager.exe

chown root:wheel /Applications/ESManager.app/ESManager
chmod 755 /Applications/ESManager.app/ESManager

su mobile -c uicache
